import os
from dotenv import load_dotenv # type: ignore
from openai import OpenAI   # type: ignore


load_dotenv()


OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

client = OpenAI(api_key=OPENAI_API_KEY)



from datetime import datetime



def rewrite_alert_with_openai(alert_text):
    messages = [
    {
        "role": "system",
        "content": (
            "You are RiskBot, a security assistant for CGS Cyber Defense. "
            "Your job is to write short, helpful alert summaries that feel like they came from a real teammate. "
            "Your tone is clear, professional, and human — not robotic, overly formal, or salesy. "
            "Write 2–4 sentence summaries explaining what's wrong, who it's affecting, and why it matters. "
            "Be concise, avoid filler text like greetings or closings, and skip redundant instructions like 'click the link'. "
            "NO emojis. NO HTML. NO bullet points. Just a clean, readable paragraph."
        )
    },
    {
        "role": "user",
        "content": f"""
Here’s the raw alert text. Write a friendly, professional paragraph to place at the top of an email:

{alert_text}
"""
    }
]

    response = client.chat.completions.create(
        model="gpt-4",  
        messages=messages,
        max_tokens=300,
        temperature=0.5,
    )

    return response.choices[0].message.content.strip()


   

def generate_html_email(summary_text, finding):
    return f"""
    <html>
      <body style='font-family: Arial, sans-serif; color: #333; background-color: #f9f9f9; padding: 30px;'>
        <div style='max-width: 700px; margin: auto; background-color: white; border-radius: 8px; box-shadow: 0 0 10px rgba(0,0,0,0.05); padding: 30px;'>

          <img src="https://i0.wp.com/cgscyberdefense.com/wp-content/uploads/2024/07/cropped-favicon.png?fit=512%2C512&ssl=1"
               alt="Logo"
               style="max-width: 120px; display: block; margin: 0 auto 20px;" />

          <h2 style='color: #d9534f; text-align: center;'>🚨 Security Alert Notification</h2>
          <p style='font-size: 16px;'>
            Hello Team,<br><br>
            {summary_text}<br><br>
            Please visit the link provided for more detailed information.
          </p>

          <hr style='margin: 30px 0;'>

          <h3 style='color: #333;'>🔍 Alert Overview</h3>
          <table style='width: 100%; font-size: 14px; border-collapse: collapse;'>
            <tr><td style='padding: 8px 0; font-weight: bold;'>Date:</td><td>{finding.get('InsertDate', 'N/A')}</td></tr>
            <tr><td style='padding: 8px 0; font-weight: bold;'>Vendor:</td><td>{finding.get('Vendor', 'Unknown')}</td></tr>
            <tr><td style='padding: 8px 0; font-weight: bold;'>Category:</td><td>{finding.get('Module', 'N/A')}</td></tr>
            <tr><td style='padding: 8px 0; font-weight: bold;'># of Findings:</td><td>1</td></tr>
            <tr><td style='padding: 8px 0; font-weight: bold;'>Focus Tag:</td><td>{finding.get('FocusTag', 'General')}</td></tr>
            <tr><td style='padding: 8px 0; font-weight: bold;'>Severity:</td>
                <td>
                    <span style="display: inline-block; background-color: {'#dc3545' if finding.get('Severity') == 'Critical' else '#ffc107'}; color: white; padding: 4px 8px; border-radius: 4px;">
                        {finding.get('Severity', 'Unknown')}
                    </span>
                </td>
            </tr>
            <tr><td style='padding: 8px 0; font-weight: bold;'>Description:</td><td>{finding.get('Title')}</td></tr>
            <tr><td style='padding: 8px 0; font-weight: bold;'>Recommended Action:</td><td>{finding.get('RecommendedAction', 'Please review and address promptly.')}</td></tr>
            <tr><td style='padding: 8px 0; font-weight: bold;'>Notes:</td><td>{finding.get('Notes', 'No additional notes.')}</td></tr>
          </table>

          <hr style='margin: 30px 0;'>

          <h3 style='color: #333;'>🔗 View in Workflow Dashboard</h3>
          <p style='font-size: 14px;'>
            You can view and take action on this alert directly in the live workflow dashboard.
          </p>
          <div style='text-align: center; margin-top: 20px;'>
            <a href="{finding.get('Url', '#')}"
               style='background-color: #0275d8; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; display: inline-block; font-weight: bold;'>
              Open Alert Dashboard
            </a>
          </div>

          <div style='margin-top: 30px; font-size: 13px; color: #555;'>
            <p><strong>Status options you can mark in the dashboard:</strong></p>
            <ul style='margin-left: 20px;'>
              <li>🟡 <strong>Not yet reviewed</strong></li>
              <li>🛠️ <strong>Working on it</strong></li>
              <li>✅ <strong>Patched</strong></li>
            </ul>
            <p>This email was generated by RiskBot Security Automation.</p>
          </div>
        </div>
      </body>
    </html>
    """